package spmotorbet;

import static java.awt.event.PaintEvent.UPDATE;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.math.RoundingMode;
import java.security.SecureRandom;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.Random;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import sun.security.util.Password;
import static javax.swing.UIManager.getString;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salvo
 */
public class SPMotorBetGUI extends javax.swing.JFrame {
    private SPMotorBet spmotorbet;

    /**
     * Creates new form SPMotorBet
     */
    public SPMotorBetGUI() {
        initComponents();
        initPannel();
        spmotorbet = SPMotorBet.getInstance();      //definisce l'istanza Singleton di SPMotorBet da utilizzare all'interno della GUI
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void  initPannel(){
        PannInsCliente2.setVisible(false);
        passlabel.setVisible(false);
        password.setVisible(false);
        msgcompletata.setVisible(false);
        riepilogo.setVisible(false);
        monitor.setVisible(false);
        PannInsCliente1.setVisible(false);
        PannInsCliente2.setVisible(false);
        PannModConto.setVisible(false);
     }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PannInsCliente1 = new javax.swing.JPanel();
        nome = new javax.swing.JTextField();
        codice_fiscale = new javax.swing.JTextField();
        data_nascita = new javax.swing.JTextField();
        indirizzo = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        prosegui = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cognome = new javax.swing.JTextField();
        home1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PannModConto = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        importo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        accredita = new javax.swing.JButton();
        Preleva = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        CodFisc = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        SaldoAttuale = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PannInsCliente2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        conferma = new javax.swing.JButton();
        indietro = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        msgcompletata = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        monitor = new javax.swing.JTextArea();
        riepilogo = new javax.swing.JLabel();
        home2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PannPrincipale = new javax.swing.JPanel();
        titolo = new javax.swing.JLabel();
        labelAdmin = new javax.swing.JLabel();
        aggiungi = new javax.swing.JButton();
        modConto = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1820, 850));

        PannInsCliente1.setMinimumSize(new java.awt.Dimension(1820, 850));
        PannInsCliente1.setLayout(null);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        PannInsCliente1.add(nome);
        nome.setBounds(520, 310, 99, 33);

        codice_fiscale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codice_fiscaleActionPerformed(evt);
            }
        });
        PannInsCliente1.add(codice_fiscale);
        codice_fiscale.setBounds(520, 400, 99, 33);
        PannInsCliente1.add(data_nascita);
        data_nascita.setBounds(520, 440, 99, 33);
        PannInsCliente1.add(indirizzo);
        indirizzo.setBounds(520, 490, 99, 33);
        PannInsCliente1.add(telefono);
        telefono.setBounds(520, 530, 99, 33);

        prosegui.setText("Prosegui");
        prosegui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proseguiActionPerformed(evt);
            }
        });
        PannInsCliente1.add(prosegui);
        prosegui.setBounds(1679, 760, 130, 33);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PannInsCliente1.add(jButton2);
        jButton2.setBounds(1510, 760, 140, 33);

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Nome");
        PannInsCliente1.add(jLabel1);
        jLabel1.setBounds(380, 320, 90, 21);

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Cognome");
        PannInsCliente1.add(jLabel2);
        jLabel2.setBounds(380, 360, 100, 21);

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Cod.Fiscale");
        PannInsCliente1.add(jLabel3);
        jLabel3.setBounds(380, 410, 120, 21);

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Data di nascita");
        PannInsCliente1.add(jLabel4);
        jLabel4.setBounds(380, 450, 130, 21);

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("gg/mm/aaaa");
        PannInsCliente1.add(jLabel5);
        jLabel5.setBounds(630, 450, 140, 21);

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Indirizzo");
        PannInsCliente1.add(jLabel6);
        jLabel6.setBounds(380, 500, 110, 21);

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Telefono");
        PannInsCliente1.add(jLabel7);
        jLabel7.setBounds(380, 530, 110, 21);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("INSERIMENTO NUOVO UTENTE");
        PannInsCliente1.add(jLabel8);
        jLabel8.setBounds(750, 100, 460, 22);

        cognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cognomeActionPerformed(evt);
            }
        });
        PannInsCliente1.add(cognome);
        cognome.setBounds(520, 350, 99, 33);

        home1.setText("HOME");
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        PannInsCliente1.add(home1);
        home1.setBounds(10, 760, 130, 33);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spmotorbet/S&p.png"))); // NOI18N
        PannInsCliente1.add(jLabel16);
        jLabel16.setBounds(50, 50, 450, 150);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spmotorbet/spmotorbet.jpg"))); // NOI18N
        jLabel15.setText("jLabel15");
        PannInsCliente1.add(jLabel15);
        jLabel15.setBounds(0, 0, 1820, 850);

        PannModConto.setMinimumSize(new java.awt.Dimension(1820, 850));
        PannModConto.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("MODIFICA CONTO");
        PannModConto.add(jLabel10);
        jLabel10.setBounds(810, 140, 360, 29);

        importo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importoActionPerformed(evt);
            }
        });
        PannModConto.add(importo);
        importo.setBounds(730, 280, 90, 33);

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Importo €");
        PannModConto.add(jLabel11);
        jLabel11.setBounds(580, 290, 140, 21);

        accredita.setText("Accredita");
        accredita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accreditaActionPerformed(evt);
            }
        });
        PannModConto.add(accredita);
        accredita.setBounds(1040, 280, 180, 33);

        Preleva.setText("Preleva");
        Preleva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrelevaActionPerformed(evt);
            }
        });
        PannModConto.add(Preleva);
        Preleva.setBounds(1040, 330, 180, 33);

        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Codice Fiscale");
        PannModConto.add(jLabel12);
        jLabel12.setBounds(580, 220, 140, 21);
        PannModConto.add(CodFisc);
        CodFisc.setBounds(730, 220, 146, 33);

        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        PannModConto.add(home);
        home.setBounds(60, 720, 150, 33);
        PannModConto.add(SaldoAttuale);
        SaldoAttuale.setBounds(730, 330, 90, 33);

        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Saldo €");
        PannModConto.add(jLabel13);
        jLabel13.setBounds(580, 340, 120, 21);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spmotorbet/S&p.png"))); // NOI18N
        PannModConto.add(jLabel20);
        jLabel20.setBounds(60, 50, 500, 140);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spmotorbet/subaru-impreza-wrc.png"))); // NOI18N
        PannModConto.add(jLabel19);
        jLabel19.setBounds(0, 0, 1820, 850);

        PannInsCliente2.setMinimumSize(new java.awt.Dimension(1820, 850));
        PannInsCliente2.setLayout(null);

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Inserisci Username ");
        PannInsCliente2.add(jLabel9);
        jLabel9.setBounds(487, 290, 180, 21);

        conferma.setText("Conferma");
        conferma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermaActionPerformed(evt);
            }
        });
        PannInsCliente2.add(conferma);
        conferma.setBounds(1676, 730, 140, 33);

        indietro.setText("Indietro");
        indietro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indietroActionPerformed(evt);
            }
        });
        PannInsCliente2.add(indietro);
        indietro.setBounds(1533, 730, 130, 33);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        PannInsCliente2.add(username);
        username.setBounds(690, 290, 131, 33);

        msgcompletata.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        msgcompletata.setForeground(new java.awt.Color(204, 0, 0));
        msgcompletata.setText("REGISTRAZIONE COMPLETATA");
        PannInsCliente2.add(msgcompletata);
        msgcompletata.setBounds(460, 450, 410, 22);

        passlabel.setForeground(java.awt.Color.white);
        passlabel.setText("Password:");
        PannInsCliente2.add(passlabel);
        passlabel.setBounds(557, 360, 110, 21);

        password.setEditable(false);
        PannInsCliente2.add(password);
        password.setBounds(690, 360, 122, 33);

        monitor.setColumns(20);
        monitor.setRows(5);
        jScrollPane1.setViewportView(monitor);

        PannInsCliente2.add(jScrollPane1);
        jScrollPane1.setBounds(950, 290, 255, 181);

        riepilogo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        riepilogo.setForeground(java.awt.Color.white);
        riepilogo.setText("RIEPILOGO");
        PannInsCliente2.add(riepilogo);
        riepilogo.setBounds(950, 240, 350, 25);

        home2.setText("HOME");
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        PannInsCliente2.add(home2);
        home2.setBounds(30, 740, 120, 33);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spmotorbet/S&p.png"))); // NOI18N
        PannInsCliente2.add(jLabel18);
        jLabel18.setBounds(10, 60, 600, 120);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spmotorbet/spmotorbet.jpg"))); // NOI18N
        PannInsCliente2.add(jLabel17);
        jLabel17.setBounds(0, 0, 1820, 850);

        PannPrincipale.setMinimumSize(new java.awt.Dimension(1820, 850));
        PannPrincipale.setLayout(null);

        titolo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titolo.setForeground(java.awt.Color.white);
        titolo.setText("S&P MotorBet");
        PannPrincipale.add(titolo);
        titolo.setBounds(790, 220, 188, 29);

        labelAdmin.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        labelAdmin.setForeground(java.awt.Color.white);
        labelAdmin.setText("Admin");
        PannPrincipale.add(labelAdmin);
        labelAdmin.setBounds(1670, 760, 70, 21);

        aggiungi.setText("NUOVO CLIENTE");
        aggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiActionPerformed(evt);
            }
        });
        PannPrincipale.add(aggiungi);
        aggiungi.setBounds(650, 360, 148, 33);

        modConto.setText("MODIFICA CONTO");
        modConto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modContoActionPerformed(evt);
            }
        });
        PannPrincipale.add(modConto);
        modConto.setBounds(940, 360, 230, 33);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spmotorbet/spmotorbet.png"))); // NOI18N
        PannPrincipale.add(jLabel14);
        jLabel14.setBounds(0, 0, 1820, 850);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1820, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PannInsCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 1820, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PannModConto, javax.swing.GroupLayout.DEFAULT_SIZE, 1820, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PannInsCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, 1820, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PannPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, 1820, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PannInsCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(PannModConto, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PannInsCliente2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PannPrincipale, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proseguiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proseguiActionPerformed
        if(!(nome.getText().trim().isEmpty()||cognome.getText().trim().isEmpty()||indirizzo.getText().trim().isEmpty()||
                codice_fiscale.getText().trim().isEmpty()||telefono.getText().trim().isEmpty()||data_nascita.getText().trim().isEmpty())){
            if(nome.getText().matches(".*\\d+.*") || cognome.getText().matches(".*\\d+.*") ){
                JOptionPane.showMessageDialog(null, "Errore: immettere valori validi per nome e/o cognome", "Error", JOptionPane.ERROR_MESSAGE);
                nome.setText("");
                cognome.setText("");
            }else{
                if(!telefono.getText().matches(".*\\D+.*")){
                    int controllo = spmotorbet.InsNuovoCliente(nome.getText(), cognome.getText(), indirizzo.getText(), codice_fiscale.getText(), telefono.getText(), data_nascita.getText());
                    if(controllo==1){                           //cliente non presente nella listaClienti, tutto OK, si procede con l'inserimento
                            PannPrincipale.setVisible(false);
                            PannInsCliente1.revalidate();
                            PannInsCliente1.updateUI();
                            PannInsCliente1.setVisible(false);
                            PannInsCliente2.setVisible(true);
                            PannInsCliente2.revalidate();
                            PannInsCliente2.updateUI();
                    }else{
                        if(controllo == 2){                     //cliente già presente nella listaClienti
                            JOptionPane.showMessageDialog(null, "Errore: cliente già esistente", "Error", JOptionPane.ERROR_MESSAGE);
                            nome.setText("");
                            cognome.setText("");
                            codice_fiscale.setText("");
                            telefono.setText("");
                            indirizzo.setText("");
                            data_nascita.setText("");
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "Errore: immettere la data nel formato corretto gg/mm/aaaa", "Error", JOptionPane.ERROR_MESSAGE);
                            data_nascita.setText("");
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Errore: immettere valore valido per il numero di telefono", "Error", JOptionPane.ERROR_MESSAGE);
                    telefono.setText("");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Errore: immettere i dati mancanti.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_proseguiActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void codice_fiscaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codice_fiscaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codice_fiscaleActionPerformed

    private void cognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cognomeActionPerformed

    private void confermaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaActionPerformed
        if(!(username.getText().trim().isEmpty())){
            DateFormat format2 = new SimpleDateFormat("dd/MM/yyyy");
            boolean res = spmotorbet.ConfermaIscrizione(username.getText(), format2);
            if(res){
                passlabel.setVisible(true);
                password.setVisible(true);
                msgcompletata.setVisible(true);
                password.setText(spmotorbet.cliente.getPassword());
                indietro.setEnabled(false);
                conferma.setEnabled(false);
                riepilogo.setVisible(true);
                username.setEditable(false);
                monitor.setVisible(true);
                monitor.setText("COGNOME: "+spmotorbet.getClienteCorrente().getCognome()+"\nNOME: "+spmotorbet.getClienteCorrente().getNome()+"\nCODICE FISCALE: "+spmotorbet.getClienteCorrente().getCodicefiscale()+"\nDATA DI NASCITA: "+format2.format(spmotorbet.getClienteCorrente().getData_di_nascita())+"\nINDIRIZZO: "+spmotorbet.getClienteCorrente().getIndirizzo()+"\nTELEFONO: "+spmotorbet.getClienteCorrente().getTelefono());
            }else{
                JOptionPane.showMessageDialog(null, "Errore: inserimento fallito", "Error", JOptionPane.ERROR_MESSAGE);
            }
            }else{
            JOptionPane.showMessageDialog(null, "Errore: immettere username valido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confermaActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void indietroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indietroActionPerformed
        username.setText("");
        password.setText("");
        riepilogo.setText("");
        data_nascita.setText("");
        PannInsCliente2.setVisible(false);
        PannInsCliente1.setVisible(true);
        PannInsCliente1.revalidate();
        PannInsCliente1.updateUI();
    }//GEN-LAST:event_indietroActionPerformed

    private void modContoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modContoActionPerformed
        PannModConto.setVisible(true);
        PannPrincipale.setVisible(false);
    }//GEN-LAST:event_modContoActionPerformed

    private void aggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiActionPerformed
        PannPrincipale.setVisible(false);
        PannInsCliente1.setVisible(true);
        PannInsCliente1.revalidate();
        PannInsCliente1.updateUI();
       
    }//GEN-LAST:event_aggiungiActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        PannPrincipale.setVisible(true);
        PannModConto.setVisible(false);
        CodFisc.setText("");
        importo.setText("");
        SaldoAttuale.setText("");
    }//GEN-LAST:event_homeActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        PannPrincipale.setVisible(true);
        PannInsCliente1.setVisible(false);
        PannPrincipale.revalidate();
        PannPrincipale.updateUI();
        nome.setText("");
        cognome.setText("");
        codice_fiscale.setText("");
        indirizzo.setText("");
        telefono.setText("");
    }//GEN-LAST:event_home1ActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        PannPrincipale.setVisible(true);
        PannInsCliente1.setVisible(false);
        PannInsCliente2.setVisible(false);
        PannPrincipale.revalidate();
        PannPrincipale.updateUI();
        nome.setText("");
        cognome.setText("");
        codice_fiscale.setText("");
        indirizzo.setText("");
        telefono.setText("");
        riepilogo.setText("");
        username.setEditable(true);
        username.setText("");
        password.setText("");
        passlabel.setVisible(false);
        indietro.setEnabled(true);
        conferma.setEnabled(true);
    }//GEN-LAST:event_home2ActionPerformed
    
    private void accreditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accreditaActionPerformed
        
        DecimalFormat df = new DecimalFormat("#.00");
        df.setGroupingSize(3);
        
        if(!(CodFisc.getText().trim().isEmpty()||importo.getText().trim().isEmpty())){
            //try{
                try{
                    String impformatted = df.format(Float.parseFloat(importo.getText())); //Stringa di appoggio per effettuare il troncamento a due cifre decimali e la sostituzione di , con .
                    impformatted = impformatted.replace(",", ".");
                    float imp = Float.parseFloat(impformatted);
                    float saldoFin = spmotorbet.accredita(CodFisc.getText(), imp);
                    if (saldoFin == -1){                //Errore, Codice Fiscale e Cliente non presenti nella listaClienti
                        JOptionPane.showMessageDialog(null, "Errore: codice fiscale non presente nel sistema.", "Error", JOptionPane.ERROR_MESSAGE);
                        CodFisc.setText("");
                        SaldoAttuale.setText("");
                    }else{
                        SaldoAttuale.setText(Float.toString(saldoFin));
                    }
                }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Errore: inserire importo numerico", "Error", JOptionPane.ERROR_MESSAGE);
                }
        }else{
            JOptionPane.showMessageDialog(null, "Errore: immettere i dati mancanti.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_accreditaActionPerformed

    private void PrelevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrelevaActionPerformed
        
        DecimalFormat df = new DecimalFormat("#.00");
        df.setGroupingSize(3);
                
        if(!(CodFisc.getText().trim().isEmpty()||importo.getText().trim().isEmpty())){
            try{
                String impformatted = df.format(Float.parseFloat(importo.getText())); //Stringa di appoggio per effettuare il troncamento a due cifre decimali e la sostituzione di , con .
                impformatted = impformatted.replace(",", ".");
                float imp = Float.parseFloat(impformatted);
                float saldoFin = spmotorbet.preleva(CodFisc.getText(), imp);
                if (saldoFin == -1){                    //Errore, Codice Fiscale e Cliente non presenti nella listaClienti
                    JOptionPane.showMessageDialog(null, "Errore: codice fiscale non presente nel sistema.", "Error", JOptionPane.ERROR_MESSAGE);
                    CodFisc.setText("");
                    SaldoAttuale.setText("");
                }else{
                    if(saldoFin == -2){                 //Errore, saldo sul conto personale del Cliente non sufficiente a coprire il prelievo
                        JOptionPane.showMessageDialog(null, "Errore: saldo insufficiente a coprire il prelievo", "Error", JOptionPane.ERROR_MESSAGE);
                    }else{
                        SaldoAttuale.setText(Float.toString(saldoFin));
                        SaldoAttuale.setEditable(false);
                    }                   
                }
            }catch(NumberFormatException e){
                            JOptionPane.showMessageDialog(null, "Errore: inserire importo numerico", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Errore: immettere i dati mancanti.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_PrelevaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        nome.setText("");
        cognome.setText("");
        codice_fiscale.setText("");
        indirizzo.setText("");
        telefono.setText("");
        data_nascita.setText(""); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void importoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importoActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[])  {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPMotorBetGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodFisc;
    private javax.swing.JPanel PannInsCliente1;
    private javax.swing.JPanel PannInsCliente2;
    private javax.swing.JPanel PannModConto;
    private javax.swing.JPanel PannPrincipale;
    private javax.swing.JButton Preleva;
    private javax.swing.JTextField SaldoAttuale;
    private javax.swing.JButton accredita;
    private javax.swing.JButton aggiungi;
    private javax.swing.JTextField codice_fiscale;
    private javax.swing.JTextField cognome;
    private javax.swing.JButton conferma;
    private javax.swing.JTextField data_nascita;
    private javax.swing.JButton home;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JTextField importo;
    private javax.swing.JButton indietro;
    private javax.swing.JTextField indirizzo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JButton modConto;
    private javax.swing.JTextArea monitor;
    private javax.swing.JLabel msgcompletata;
    private javax.swing.JTextField nome;
    private javax.swing.JLabel passlabel;
    private javax.swing.JTextField password;
    private javax.swing.JButton prosegui;
    private javax.swing.JLabel riepilogo;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel titolo;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
